version: "3"
services:
  database:
    container_name: devenv-db
    image: mariadb:latest
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql:rw
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    networks:
      - backend
    restart: always
  api:
    container_name: devenv-minimalapi
    image: devenv-api
    ports:
      - 5000:80
    networks:
      - backend
    restart: always

networks:
  backend:
    name: devenv-backend-network  
    driver: bridge

         